"""Build the GameCube controller feature for Super Mario Galaxy 2."""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_common as g
from layout import GC_BASE, GC_END
from ops import Blob, Feature, Hook, Patch, b_insn

SITES = {
    'SB4E01': dict(
        kpad_read=0x804CF884,
        probe=0x805EB410,
        ext_check=0x804CE3B0,
        panic1=0x804B7D90,
        panic2=0x804B7E54,
        panic3=0x805B66B4,
    ),
    'SB4P01': dict(
        kpad_read=0x804CF884,
        probe=0x805EB410,
        ext_check=0x804CE3B0,
        panic1=0x804B7D90,
        panic2=0x804B7E54,
        panic3=0x805B66B4,
    ),
    'SB4J01': dict(
        kpad_read=0x804CF884,
        probe=0x805EB410,
        ext_check=0x804CE3B0,
        panic1=0x804B7D90,
        panic2=0x804B7E54,
        panic3=0x805B66B4,
    ),
    'SB4K01': dict(
        kpad_read=0x804CF914,
        probe=0x805EB890,
        ext_check=0x804CE440,
        panic1=0x804B7E00,
        panic2=0x804B7EC4,
        panic3=0x805B67B4,
    ),
    'SB4W01': dict(
        kpad_read=0x804CF914,
        probe=0x805EB890,
        ext_check=0x804CE440,
        panic1=0x804B7E00,
        panic2=0x804B7EC4,
        panic3=0x805B67B4,
    ),
}

def generate_float_table():
    lines = []
    for i in range(256):
        disp = i - 128
        if abs(disp) < 8:
            val = 0.0
        else:
            val = max(-1.0, min(1.0, disp / 100.0))
        lines.append(f'    .float {val:.6f}')
    return '\n'.join(lines) + '\n'

def build(region, dol):
    sites = SITES[region]
    
    # Generate stick table and append to gc_code.s
    src = g.read('gc_code.s')
    src = src.replace('# 256 pre-computed float values generated by gen_gc.py', generate_float_table())
    
    syms = {
        'KPAD_READ_RET': sites['kpad_read'] + 4,
        'WPAD_PROBE_BODY': sites['probe'] + 4,
    }
    
    import asm
    gc_bytes, symbols = asm.assemble_symbols(src, GC_BASE, syms, {})
    
    if GC_BASE + len(gc_bytes) > GC_END:
        raise SystemExit(f'gc code overflows window: 0x{GC_BASE + len(gc_bytes):X} > 0x{GC_END:X}')
        
    ops = []
    # 1. Injected blob in cave
    ops.append(Blob(GC_BASE, gc_bytes, note='GameCube controller driver and stick calibration table'))
    
    # 2. Hook at KPADRead return
    orig_kpad_read = dol.read(sites['kpad_read'], 4)
    b_kpad_read = b_insn(symbols['gc_kpad_read_hook'], sites['kpad_read'])
    ops.append(Patch(
        sites['kpad_read'],
        struct.pack('>I', b_kpad_read),
        orig_kpad_read,
        note='KPADRead return hook: inject GC controller inputs into KPADStatus'
    ))
    
    # 3. Hook at WPADProbe
    orig_probe = dol.read(sites['probe'], 4)
    b_probe = b_insn(symbols['gc_probe_hook'], sites['probe'])
    ops.append(Patch(
        sites['probe'],
        struct.pack('>I', b_probe),
        orig_probe,
        note='WPADProbe hook: report GC controller as connected'
    ))
    
    # 4. Extension check: allow extension 2
    orig_ext = dol.read(sites['ext_check'], 8)
    ops.append(Patch(
        sites['ext_check'],
        bytes.fromhex('2c1e000240810014'),
        orig_ext,
        note='Controller manager: allow extension type 2 (Classic Controller)'
    ))
    
    # 5. Panic handlers nop
    nop = bytes.fromhex('60000000')
    ops.append(Patch(sites['panic1'], nop, dol.read(sites['panic1'], 4), note='Panic handler 1 disable'))
    ops.append(Patch(sites['panic2'], nop, dol.read(sites['panic2'], 4), note='Panic handler 2 disable'))
    ops.append(Patch(sites['panic3'], nop, dol.read(sites['panic3'], 4), note='Panic handler 3 disable'))
    
    return Feature('gc', 'GameCube controller', region, ops)
